openapi: 3.1.0
info:
  title: Pokemon API
  version: 0.1.1
paths:
  /pokemon:
    get:
      summary: Get pokemon
      description: Provides basic details on all pokemon
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 721
                items:
                  type: object
                  properties:
                    pokedex-number:
                      type: integer
                      description: The index number of this pokemon in the pokedex
                    name:
                      type: string
                      description: The name of this pokemon in the pokedex
