openapi: 3.1.0
info:
  title: Pokemon API
  version: 0.1.0
paths:
  /pokemon:
    get:
      summary: Get pokemon
      description: Provides basic details on all pokemon
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  pokedex-number:
                    type: integer
                  name:
                    type: string
