openapi: 3.1.0
info:
  title: Pokemon API
  version: 0.3.1
paths:
  /pokemon:
    get:
      summary: Get pokemon
      description: Provides basic details on all pokemon
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 721
                items:
                  type: object
                  properties:
                    "#":
                      type: integer
                      description: The index number of this pokemon in the pokedex
                    name:
                      type: string
                      description: The name of this pokemon in the pokedex
  /pokemon/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          description: The pokedex index number of the target pokemon
          schema:
            type: integer
            minimum: 1
            maximum: 721
      responses:
        "200":
          description: "OK"
        "400":
          description: The parameter received was not valid
          content:
            text/html:
              schema:
                type: string
              example: The ID must be an integer from 1 to 721